ALTER TYPE "AuditAction" ADD VALUE 'TEAM_CONFIRMED';
ALTER TYPE "AuditAction" ADD VALUE 'TEAM_CLOSED';
ALTER TYPE "AuditAction" ADD VALUE 'REPORT_APPROVED';
ALTER TYPE "AuditAction" ADD VALUE 'REPORT_REVISION_REQUESTED';
